# Generated by Django 3.2.5 on 2021-08-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile_img'),
        ),
    ]
